#!/usr/bin/env bash
# Test Helper Script - Quick reference for running tests

echo "╔═══════════════════════════════════════════════════════════╗"
echo "║         TriageAssist Testing Quick Reference             ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""

# Color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}Available Commands:${NC}"
echo ""
echo -e "${GREEN}Run all tests:${NC}"
echo "  npm test"
echo ""
echo -e "${GREEN}Run tests in watch mode:${NC}"
echo "  npm run test:watch"
echo ""
echo -e "${GREEN}Generate coverage report:${NC}"
echo "  npm run test:coverage"
echo ""
echo -e "${GREEN}Run specific test file:${NC}"
echo "  npm test -- Button.test.tsx"
echo "  npm test -- __tests__/hooks/use-mobile.test.ts"
echo ""
echo -e "${GREEN}Run tests matching pattern:${NC}"
echo "  npm test -- --testNamePattern=\"Login\""
echo "  npm test -- --testNamePattern=\"Button\""
echo ""
echo -e "${GREEN}Run tests in specific directory:${NC}"
echo "  npm test -- __tests__/components"
echo "  npm test -- __tests__/api"
echo ""
echo -e "${GREEN}Run with verbose output:${NC}"
echo "  npm test -- --verbose"
echo ""
echo -e "${GREEN}Run integration tests only:${NC}"
echo "  npm test -- __tests__/integration"
echo ""
echo -e "${GREEN}Run API tests only:${NC}"
echo "  npm test -- __tests__/api"
echo ""
echo -e "${YELLOW}Test Categories:${NC}"
echo ""
echo "  Unit Tests:"
echo "    - Utils & Types: __tests__/lib"
echo "    - Hooks: __tests__/hooks"
echo "    - Components: __tests__/components"
echo "    - Providers: __tests__/providers"
echo ""
echo "  API Tests:"
echo "    - Routes: __tests__/api"
echo ""
echo "  Integration Tests:"
echo "    - Auth Flow: __tests__/integration/auth-flow.test.ts"
echo "    - Scenario Management: __tests__/integration/scenario-management.test.ts"
echo ""
echo -e "${BLUE}Test Files (18 total):${NC}"
echo ""
echo "  Components (9 files):"
echo "    ✓ Button.test.tsx (9 tests)"
echo "    ✓ Card.test.tsx (8 tests)"
echo "    ✓ Input.test.tsx (9 tests)"
echo "    ✓ ThemeToggle.test.tsx (6 tests)"
echo "    ✓ LoginForm.test.tsx (8 tests)"
echo "    ✓ SignupForm.test.tsx (8 tests)"
echo "    ✓ FormComponents.test.tsx (11 tests)"
echo "    ✓ DialogComponents.test.tsx (12 tests)"
echo "    ✓ SelectAndDisplay.test.tsx (14 tests)"
echo ""
echo "  Hooks (2 files):"
echo "    ✓ use-mobile.test.ts (7 tests)"
echo "    ✓ use-pointer-location.test.ts (8 tests)"
echo ""
echo "  Utilities (2 files):"
echo "    ✓ utils.test.ts (9 tests)"
echo "    ✓ types.test.ts (14 tests)"
echo ""
echo "  Providers (1 file):"
echo "    ✓ supabase-client.test.ts (25 tests)"
echo ""
echo "  API Routes (2 files):"
echo "    ✓ access-request.test.ts (6 tests)"
echo "    ✓ scenarios.test.ts (8 tests)"
echo ""
echo "  Integration (2 files):"
echo "    ✓ auth-flow.test.ts (15 tests)"
echo "    ✓ scenario-management.test.ts (15 tests)"
echo ""
echo -e "${YELLOW}Total: 200+ tests${NC}"
echo ""
echo -e "${BLUE}Documentation:${NC}"
echo "  - TESTING.md: Comprehensive testing guide"
echo "  - TEST_SUMMARY.md: Overview of all tests"
echo ""
echo -e "${GREEN}✓ Setup complete!${NC}"
echo ""
